apiVersion: v1
kind: Secret
metadata:
  name: {{ include "surrealdb.fullname" . }}
  labels:
    {{- include "surrealdb.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ default "root" .Values.config.username | quote }}
  password: {{ default (randAlphaNum 32) .Values.config.password | quote }}
  {{- if and .Values.persistence.enabled .Values.persistence.encryptionKey }}
  encryptionKey: {{ .Values.persistence.encryptionKey | quote }}
  {{- end }}
