name: Lint & Template

on: [workflow_dispatch, push]

jobs:
  lint-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
        with:
          token: ${{ github.token }}
      - run: helm version
      - run: helm lint .
      - run: helm template surrealdb .
